domain: example.com
url: https://example.com
baseurl: ""

title: 
email: work.atmadipg@gmail.com
author: Atmadip Goswami

lang: en

plugins:
  - jekyll-seo-tag

color: "#13ccf9"

rrss:
  email: "work.atmadipg@gmail.com"
  x: "https://x.com/hopelessbhai"
  linkedin: "https://discord.com/"
  github: "https://github.com/HopelessBhai"
